### ISSUE TITLE
0.4.6 conflict with OptiFabric

### ISSUE THREAD

**Issue by Dyiing** [hashalite/Freecam#10]
Attempting to run version v0.4.6 alongside OptiFabric 1.12.10 results in a mixin crash. Only tested on 1.18.1. Error no longer occurs when OptiFabric is removed, or when reverting to v0.4.5.

Fabric Loader 0.13.3

Mods: 
\- fabric-api-0.46.4+1.18
\- freecam-0.4.6+1.18
\- optifabric-1.12.10_1 (OptiFine_1.18.1_HD_U_H4_4)

log: https://paste.ee/p/6NLwn

**Comment by hashalite** [comment]
Thanks for reporting. This has been fixed in 0.4.7.
