### ISSUE TITLE
freecam has collision when collision settings are all set to ignore

### ISSUE THREAD

**Issue by Cujoplays** [hashalite/Freecam#104]
when i enter freecam i can not use the freecam to travel through blocks even though the first three options in collision are all on yes.  this is on a server and other members of the server are able to travel through blocks.

**Comment by hashalite** [comment]
If you downloaded the mod from Modrinth, noclip is disabled in multiplayer to comply with their rules. If you would like to use noclip in multiplayer, download the mod from Curseforge or Github.
