### ISSUE TITLE
How to control player

### ISSUE THREAD

**Issue by lmiki9** [hashalite/Freecam#106]
I cant find any option to set a keybind for controlling the player. how can i do it?

**Comment by lmiki9** [comment]
im in 1.20.1 fabric api 0.86

**Comment by TerminalCalamitas** [comment]
The option should be at the bottom of the Minecraft keybindings settings page and is the second in the group as shown in the picture.

![image](https://github.com/hashalite/Freecam/assets/63129878/9a4c9f2f-27bc-413f-9390-0a942294adcb)
