### ISSUE TITLE
Neoforge

### ISSUE THREAD

**Issue by MattSturgeon** [hashalite/Freecam#133]
The current consensus in forge modding is to migrate away from Lex's Forge and instead use Neoforge, which is maintained by the majority of the original forge team.

Many projects are outright switching and dropping Forge support. Some with 1.20.4, some already have done in a previous release, others plan to do so in a future release.

Some projects are maintaining both Forge & Neoforge. In the short term, this is probably best for users. However, long term it'd be better if the most popular mods were Neoforge exclusive, as this would hopefully reduce fragmentation in the ecosystem.

Supporting both isn't a big deal; we would simply add a `:neoforge` gradle project. Most of the code would be identical to `:forge` however.

It is possible to have a shared `:forge-like` where shared code/mixins can live, however it is a bit cumbersome and requires custom mappings patches due to some Forge/Neoforge differences.

So long as the forge-like code is small, I think it's simpler to just duplicate it across both Forge projects. Especially if you plan on dropping one of those projects later.

See the [Architectury migration guide](https://docs.architectury.dev/api/migration/neoforge#migrate_your_architectury_project_to_neoforge) for more detail.

**Comment by hashalite** [comment]
I will definitely migrate to NeoForge in a future release (maybe the next one). I agree that we should aim to prevent fragmentation in the modding community, so when I do migrate, LexForge support will be dropped entirely for all versions supported by NeoForge.
