### ISSUE TITLE
Make the player crouch while in freecam

### ISSUE THREAD

**Issue by TheOneAndOnlyDanSan** [hashalite/Freecam#15]
Make the player crouch while in freecam if the player was crouching before

**Comment by hashalite** [comment]
I don't see the use for this. Could you provide some more information?

**Comment by hashalite** [comment]
Is this what you mean?

https://user-images.githubusercontent.com/71229440/158272215-afb1d6b1-9473-49e3-911e-1edf6ade4907.mp4

**Comment by TheOneAndOnlyDanSan** [comment]
yes. the point of this is to hide the name tag

**Comment by hashalite** [comment]
I see. I'll add this in the next update

**Comment by hashalite** [comment]
Added in 0.4.9.
