### ISSUE TITLE
1.0.2 version fails 1.18.2 check

### ISSUE THREAD

**Issue by mdedmon** [hashalite/Freecam#18]
Tried upgrading from the 1.0.1 version to 1.0.2 version and MultiMC is giving me the error below. Put the 1.0.1 version back and NO problem.   

(also posted this in the curseforge comments before I saw your note about using Git.)
 

Incompatible mod set!Incompatible mod set!net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!A potential solution has been determined: - Replace mod 'Freecam' (freecam) 1.0.2 with any version that is compatible with: - minecraft 1.18.2Unmet dependency listing: - Mod 'Freecam' (freecam) 1.0.2 requires any version between 1.16.2 (inclusive) and 1.17- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2! at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) at org.multimc.EntryPoint.listen(EntryPoint.java:143) at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by hashalite** [comment]
I am unable to reproduce this issue on my side. Can you confirm that you are using the 1.18 version and not the 1.16 one?

**Comment by mdedmon** [comment]
The filename is freecam-1.0.2+1.18.jar, but I went to curseforge and
downloaded it again (same filename), but that one loads properly. Sorry for
the trouble.
