### ISSUE TITLE
Consistent Game Crash when using freecam

### ISSUE THREAD

**Issue by endustries** [hashalite/Freecam#20]
Title, just testing out a custom modpack I created and keep using free cam to test it out and see how it works and when I try to go through blocks and look around underneath me it causes the game to crash with this error. Was able to duplicate it by just going into a different area and just tried to use the free cam to explore beneath me.

[crash-2022-04-28_19.04.23-client.txt](https://github.com/hashalite/Freecam/files/8587181/crash-2022-04-28_19.04.23-client.txt)
[crash-2022-04-28_18.42.13-client.txt](https://github.com/hashalite/Freecam/files/8587185/crash-2022-04-28_18.42.13-client.txt)

**Comment by hashalite** [comment]
This is likely being caused by one of your mods. Please try removing them one at a time until it stops crashing to narrow it down.
