### ISSUE TITLE
Sneak: Toggle affects vertical camera controls

### ISSUE THREAD

**Issue by reedrs** [hashalite/Freecam#26]
When sneak is set to toggle mode in the Minecraft settings, pressing and releasing the shift key *toggles* downward movement of the freecam, rather than the usual behavior of hold-to-move. The other directional controls for freecam continue to function as normal.

Freecam 1.0.5
Minecraft 1.18.2
Fabric API 0.51.1

**Comment by reedrs** [comment]
It looks like Motion.java has the code responsible:
```
        if (freeCamera.input.sneaking) {
            velocityY -= vSpeed;
        }
```
I had a look inside `net.minecraft.client.input.KeyboardInput`, and it looks like the `sneaking` being used here is defined as `settings.sneakKey.isPressed()`, just like all the other members of KeyboardInput. So I guess Minecraft is lying about the sneak key's state when it's in toggle mode?

I don't know much about Minecraft modding. Is there somewhere else that more detailed keyboard state information can be obtained?

**Comment by hashalite** [comment]
Vanilla flight works this way too, so I am going to keep it as is.

**Comment by reedrs** [comment]
Indeed, I only just started using Sneak: Toggle, and I hadn't noticed it was vanilla behavior. According to https://bugs.mojang.com/browse/MC-163025, this is "working as intended", though to me this behavior is a bug.
