### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by Night380** [hashalite/Freecam#28]
Was not sure where to leave a idea but for a idea that would be really cool would be to be able to have the free cam out and be able to change back to the players perspective or something like that for people that want to make time laps videos but still be able to see what they are doing

**Comment by MattSturgeon** [comment]
I think you're asking for the ability to open the freecam in a seperate window?

Don't think this would be easy to implement, but it is an interesting suggestion.

In the mean time, I can think of a couple alternative ways to achieve such a timelapse:

- **A second account:** If you have a second account you can open a second minecraft instance using the other account and log in to the same server (or use "open to LAN" if singleplayer).
- **An "offline" account:** This will only work on singleplayer/open-to-LAN worlds. Some launchers (e.g. [PolyMC](https://github.com/PolyMC/PolyMC)) allow you to log into a fake "offline" account. This way you can have two players in a world, without having to purchase an additional copy of Minecraft.
- **[Replay mod](https://www.replaymod.com):** This might be a bit overkill for a static timelapse, but replaymod allows you to record you current gameplay and then go back later to position a camera. With this method, you only need a single instance of minecraft open, but you will need to learn the basics of Replay mod.

**Comment by hashalite** [comment]
I believe this is implemented, as best possible without the second window function, through the tripod feature.
