### ISSUE TITLE
Game crashes on launch after installing mod

### ISSUE THREAD

**Issue by fengshuo2004** [hashalite/Freecam#30]
I am running **Fabric 0.14.6** for **Minecraft 1.16.5**

Java 8 is installed on the system and set in PATH but Minecraft Launcher uses its own copy of java, right?

After placing file `freecam-1.0.6+1.16.jar` into the mods folder, then launching Fabric 1.16.5 using the official launcher, the game crashes without it even creating a window. The launcher says that the game crashed with **error code 1** and may be caused by invalid Java Runtime configuration. No other information is reported.

I do have some other mods installed. Here is a list:

![图片](https://user-images.githubusercontent.com/25703836/171436599-5d41af15-3bd8-4f34-97f6-4cd953de0fe1.png)

In an attempt to isolate the problem, I removed all mods except Freecam, Fabric API and ModMenu from the folder. The game still crashes on launch exactly like before. And yes, it launches and runs fine when `freecam-1.0.6+1.16.jar` is removed.

**Comment by dstrzelec** [comment]
I am also experiencing crashes. From your list above @fengshuo2004 , I use the following Mods (assuming its an incompat issue)

iris
sodium
xaeros_minimap
(and modmenu/FabricAPI obviously)

**Comment by hashalite** [comment]
@fengshuo2004 @dstrzelec please provide the crash log.

**Comment by fengshuo2004** [comment]
> @fengshuo2004 @dstrzelec please provide the crash log.

Here is the issue though: **No crash log is actually generated**

The game crashes so early during launch, the launcher only tells me that it exited with an error code of 1. No new log file is created at `C:\Users\fengshuo\AppData\Roaming\.minecraft\crash-reports` after the crash.

![图片](https://user-images.githubusercontent.com/25703836/172921613-f1ea0158-85ac-47aa-9110-31f624af1aae.png)

This is precisely what the launcher shows after the crash. Sorry my system is in Chinese. It says:

> #### Error
> ### Game crashed
> An unknown error caused the game to crash. Sorry for the inconvinience.
> The crash may be caused by invalid Java runtime configurations. Please check all customised config settings.
> Termination code: 1
>
> **[ Copy error code ]** [ Close ]

Pressing "Copy error code" simply copies the number "1" to my clipboard. I know, not helpful.

Also launch configs of this fabric instance is kept default, I didn't change anything.

Tried launching from the command line `java -jar fabric-loader-0.14.6-1.16.5.jar` (btw the Java invoked in this command is probably not the same version the launcher uses). This time it prints `Error: Could not find or load main class net.minecraft.client.Main` before exiting.

**Comment by hashalite** [comment]
I have just fixed a 1.16 crash in version 1.0.7. Try it out and let me know if it fixes your issue.

**Comment by fengshuo2004** [comment]
Glad to report: yes it has been FIXED in v1.0.7! Now the game launches fine and freecam works. Thank you.
