### ISSUE TITLE
Would you be against me releasing my fork on Modrinth?

### ISSUE THREAD

**Issue by moxvallix** [hashalite/Freecam#33]
I have recently forked this project such that I can add it to my [Modrinth](https://modrinth.com/) modpack.

Modrinth have quite strict rules, and I needed to patch the mod to remove noclip in order to add it to my modpack.

Now that it has been approved in my modpack, I am wondering if you would be against me uploading the patched fork to Modrinth as it's own project? 

It will have a link to this original repo, and make it clear that the code was not written by me.

**Comment by hashalite** [comment]
I have plans to do something similar in the future, so I would prefer you not upload it.

**Comment by moxvallix** [comment]
Sweet thx. I have updated my modpack accordingly.
