### ISSUE TITLE
Control Player Mode doesn't deal with mouse input as a player

### ISSUE THREAD

**Issue by hackermuffin** [hashalite/Freecam#37]
When going into control player mode, only keyboard inputs are translated to be input as the player, while mouse interactions still target the block/entity the freecam is targetting.

Is it possible to have a mode where the camera is in freecam, but mouse input behaves as if it's from the player?

The use case I have in mind is for an AFK mob farm, where I want to be able to keep attacking, but also watch the farm in a freecam?

Thanks for all your work on a great mod!

**Comment by hashalite** [comment]
Thanks for the suggestion, this has been added in the next update.
