### ISSUE TITLE
Eating food under freecam causes game to crash

### ISSUE THREAD

**Issue by fengshuo2004** [hashalite/Freecam#38]
As stated above.

## To reproduce

1. Press X to toggle on freecam mode
2. Scroll to a food item in your hotbar
3. Hold right mouse button to eat food
4. Game freezes for a second, then quits

Launcher shows error:

> The game crashed whilst ticking entity
> Error: java.lang.IllegalArgumentException: Invalid hand null
> 结束代码：-1

Here's the crash report: [crash-2022-06-23_20.53.52-client.txt](https://github.com/hashalite/Freecam/files/8970437/crash-2022-06-23_20.53.52-client.txt)

This occurs in both creative and survival, singleplayer and multiplayer. Tested on 1.16.5.

**Comment by hashalite** [comment]
This will be fixed in the next update.
