### ISSUE TITLE
Free camera "player" is visible trough shaders

### ISSUE THREAD

**Issue by PinguLinux** [hashalite/Freecam#47]
![imagen](https://user-images.githubusercontent.com/55950650/188283554-a90af861-0fff-45d0-87a3-f5f3af66cd21.png)

**Comment by hashalite** [comment]
1. What version of freeccam are you using?
2. Iris or Optifabric?
3. What shaderpack?

**Comment by PinguLinux** [comment]
1. Latest
2. Iris
3. Sildur's Enhanced Default v1.14 fast

**Comment by PinguLinux** [comment]
Found out how to reproduce:
Just change to any of the 9 custom cameras

**Comment by hashalite** [comment]
Still unable to reproduce this for some reason, but I'm pretty sure I found the cause. Can you build the latest version from here and see if its fixed?

**Comment by PinguLinux** [comment]
i don't know how to build it

**Comment by PinguLinux** [comment]
ok, i figured how to build it and the bug was fixed
