### ISSUE TITLE
After launching the game, you cannot hear item pickup sounds

### ISSUE THREAD

**Issue by Minikiin** [hashalite/Freecam#5]
Versions: FreeCam 0.3.2 - 1.18.1
Fabric Loader 0.12.12 (1.18.1)

There _might_ be another sound it disables but my memory is bad so idk, might just be the item pickup one.

Steps to reproduce:
1. Run the game
2. Join singleplayer or multiplayer and drop an item, when you pick it up you won't hear the sound
3. Go into freecam and exit freecam, now you can hear item pick up sounds, even if you rejoin singleplayer/multiplayer
4. _Close game and repeat_

**Comment by hashalite** [comment]
Fixed in 0.3.3
