### ISSUE TITLE
Freecam mod not showing player (Fabric 1.19)

### ISSUE THREAD

**Issue by JimothyMartinTung** [hashalite/Freecam#51]
The mod mostly works as expected, except that the player disappears when I toggle freecam on. The player is invisible, including any armor that they are wearing, although the item that they are holding still appears.

https://ibb.co/QFdNG68

I tried to troubleshoot this by removing all other mods (except for Fabric API), but the same issue still occurs.

**Comment by hashalite** [comment]
This is a bug in 1.1.5, its fixed in 1.1.6.
