### ISSUE TITLE
(Suggestion) Freecam Tripod Memory

### ISSUE THREAD

**Issue by GizmoTechnics** [hashalite/Freecam#52]
Is it possible to create a cache that saves tripod cameras in there place? When I travel to the nether they reset in the overworld. Would it also be possible to have different saves for each dimension as well? If this is possible, can there also be a way to reset a camera or like delete it so you can easily change it's spot?

**Comment by hashalite** [comment]
I am planning on making some changes to the tripod function soon, I will consider both of these ideas.

**Comment by hashalite** [comment]
@GizmoTechnics There is now a way to reset tripods in 1.1.7. Just set the 'Reset Tripod' keybind in the controls menu, and hold it down + whichever number you want to reset.

As for per-dimension tripods, that may come in a future update.

**Comment by hashalite** [comment]
I have added separate tripods for each dimension in the next update.
