### ISSUE TITLE
Impossible to translate all strings

### ISSUE THREAD

**Issue by Loweredgames** [hashalite/Freecam#53]
there are some missing strings in the original translation. it is impossible to translate.

**Comment by hashalite** [comment]
Do you mean the setting descriptions and config GUI title? If so, I plan on adding entries for those in the language file soon.

**Comment by hashalite** [comment]
@Loweredgames I have just added all of the missing strings to the language file. There should no longer be any hard-coded strings.

If you would like to update the Italian translations, I have added  temporary English placeholder entries to the it_it file.

**Comment by Loweredgames** [comment]
done

**Comment by hashalite** [comment]
It seems like you may have missed “text.autoconfig.freecam.option.interactionMode.camera”. Would you mind checking it out?

**Comment by hashalite** [comment]
@Loweredgames could you also check out the language file for the modrinth branch? It has a few strings that are different from the main branch. It is available [here](https://github.com/hashalite/Freecam/blob/modrinth-1.19/src/main/resources/assets/freecam/lang/it_it.json).

**Comment by Loweredgames** [comment]
> It seems like you may have missed “text.autoconfig.freecam.option.interactionMode.camera”. Would you mind checking it out?

Could you update the english file @hashalite. so I update it. instead for modrinth just copy the translation file and it should work. thanks :)

**Comment by hashalite** [comment]
@Loweredgames Sorry, I’m not sure I understand

**Comment by hashalite** [comment]
@Loweredgames The modrinth version has different strings, so copying the main translation file wouldn’t work

**Comment by hashalite** [comment]
And “Camera” is still in english in the main italian file

**Comment by Loweredgames** [comment]
> And “Camera” is still in english in the [main italian file](https://github.com/hashalite/Freecam/blob/main/src/main/resources/assets/freecam/lang/it_it.json) (line 18)

"Camera" is correct.

**Comment by Loweredgames** [comment]
> @Loweredgames The modrinth version has different strings, so copying the main translation file wouldn’t work. The strings I need translated are on lines 26, 31, 32, and 35

ok, then I do.

**Comment by hashalite** [comment]
> "Camera" is correct.
 
 Ah, ok
