### ISSUE TITLE
Freecam no-clip still gets moved by pistons

### ISSUE THREAD

**Issue by Jarno-de-Wit** [hashalite/Freecam#54]
MC Version: 1.19.2
Freecam Version 1.1.6

When in freecam, even when no-clip is enabled, the camera will still get moved around by pistons / blocks moved by pistons. With "Creative" flight mode, this also includes being bounced around by slime blocks, whereas for "Default" flight mode, you will simply get pushed.

**Comment by hashalite** [comment]
This has been fixed in the next update.
