### ISSUE TITLE
Can't find the keybinds for Freecam

### ISSUE THREAD

**Issue by Imzxhir** [hashalite/Freecam#56]
Mod Version: [[Forge] Freecam 1.1.7 for MC 1.16](https://www.curseforge.com/minecraft/mc-mods/free-cam/files/4159766)
Description: Basically the title. I can't find the keybinds for the mod anywhere, I can confugre the mod but I find the keybinds.

**Comment by hashalite** [comment]
Ah you’re right, thanks for letting me know. I forgot to test the keybinds for the forge versions. I will release a hotfix soon

**Comment by hashalite** [comment]
Just released version 1.1.7.1 to fix this.
