### ISSUE TITLE
The camera occasionally teleports to 0, 0, 0

### ISSUE THREAD

**Issue by RocketLag** [hashalite/Freecam#73]
I've been using this mod on a small SMP for help with getting screenshots or viewing my build progress, and I've found that sometimes when I enable freecam, the camera teleports ~1500 blocks away to the exact origin of the world. I've observed that the bug occurs more often when the server has just started. I have not observed this bug in singleplayer.

**Comment by RocketLag** [comment]
After looking through previous posts, it looks like one of my other mods causes this. As I don't want to remove that mod, I'm just gonna deal with it.

**Comment by hashalite** [comment]
Which version of the mod are you using? This was a bug I thought I had already fixed.
