### ISSUE TITLE
Bug with pistons

### ISSUE THREAD

**Issue by AndrewG587** [hashalite/Freecam#77]
The bug is pistons can push the freecam camera.
how to reproduce:
get a piston. make a way to activate it via a repeater timer or other means
move the freecam infront of piston.
activate piston.
the camera moves.

**Comment by hashalite** [comment]
Which version of Freecam are you using? I believe this was fixed in 1.1.8

**Comment by AndrewG587** [comment]
lemme see...

**Comment by AndrewG587** [comment]
oh 1.1.5 so i should probably update
