### ISSUE TITLE
Non compatible with baritone

### ISSUE THREAD

**Issue by lostallmymoney** [hashalite/Freecam#8]
on 1.18.1 with a baritone snapshot, baritone tries moving the camera instead of the player.

**Comment by lostallmymoney** [comment]
https://github.com/cabaletta/baritone/actions/runs/1725860032

**Comment by Lord-Memester** [comment]
simply activating this freecam with baritone installed crashes the game for me, and neither can be used

**Comment by lostallmymoney** [comment]
Personally I am able to use. But when I am in freecam ordering baritone to do stuff will ed up in baritone trying to move the freecam :(
________________________________

**Comment by hashalite** [comment]
I have baritone compatibility working for the most part now. It required a large portion of the mod to be rewritten, so there are a few new bugs I need to iron out. I'll release an update in a day or two once I'm finished.

**Comment by hashalite** [comment]
Fixed in the latest update.

**Comment by lostallmymoney** [comment]
Wow nice thanks
