### ISSUE TITLE
Brightness/gamma options 

### ISSUE THREAD

**Issue by MattSturgeon** [hashalite/Freecam#82]
I noticed some users of the mod taking advantage of an edge-case where entering freecam while the player is in water causes a similar effect to Night Vision.

I'm not sure if #66 would have fixed this, but it might be useful to have a more official way of doing something similar.

This might be somewhat redundant, TBH.  I'd imagine most freecam users are aware of other mods that can control brightness. Even Mini HUD has a max-gamma toggle IIRC. But perhaps it'd be useful to be able to configure the _brightness while in freecam mode_ separately from normal brightness?

Any thoughts on whether this is useful and how you'd expect it to work would be appreciated 👍

**Comment by hashalite** [comment]
[Done](https://github.com/hashalite/Freecam/commit/18e12cfe7b689545f63ef0cd21e7aecd721e298f)
