### ISSUE TITLE
Reorganize the config?

### ISSUE THREAD

**Issue by MattSturgeon** [hashalite/Freecam#84]
As mentioned [in this comment](https://github.com/hashalite/Freecam/pull/71#issuecomment-1482140393), the config screen is starting to get a little busy and if we're not careful it could soon be overcrowded and confusing.

This inspired me to begin work on https://github.com/shedaniel/cloth-config/pull/195, but in the meantime it might be a good idea to consider how the current config could be improved.

Perhaps we could make use of tabbed category pages, collapsible sub-categoried (either expanded or collapsed by default) and other config entry types?

In the future we could also make use of dependencies to hide/disable some options when relevant.

**Comment by hashalite** [comment]
I like this idea. However, I have been considering switching to [YACL](https://github.com/isXander/YetAnotherConfigLib) since shedaniel has stated that they are done working on Cloth Config and aren't planning on adding any new features. What do you think?

**Comment by hashalite** [comment]
[Done](https://github.com/hashalite/Freecam/commit/4a4a49ffa87bcde40c3c9b7de943b8a5ac5b2f57)
