### ISSUE TITLE
Cant delete tripods

### ISSUE THREAD

**Issue by Tom-Sumner** [hashalite/Freecam#86]
Looked everywhere and cant find any documentation on how to remove a tripod camera without leaving the world / server.

**Comment by hashalite** [comment]
Unable to reproduce. Does this happen without any other mods?

**Comment by Tom-Sumner** [comment]
Yep it looks like it.

All i have in my mods folder is; fabricapi == 1.19 and freecam == 1.19

![image](https://user-images.githubusercontent.com/85069468/232138151-129be3ab-ec5e-41b0-b381-bfa9f399afa6.png)

**Comment by hashalite** [comment]
What version of Freecam/Fabric API are you using?

**Comment by hashalite** [comment]
Tripod Reset was added in 1.1.7.

**Comment by Tom-Sumner** [comment]
that would be why, thankyou.

is there a 1.19 mod that is 1.1.7?

**Comment by hashalite** [comment]
The latest version, 1.1.9, works with 1.19.4

**Comment by Tom-Sumner** [comment]
I need a 1.19.0 version. If not then I don't mind about the tripods, I rarely use them.

**Comment by hashalite** [comment]
Ah, in that case, 1.1.6 is the only version that supports 1.19.0

**Comment by Tom-Sumner** [comment]
Thankyou for clearing this up.

sorry for the waste of your time :)

**Comment by hashalite** [comment]
No problem!
