### ISSUE TITLE
freecaming below water doesn't have fog

### ISSUE THREAD

**Issue by OldWorldOrdr** [hashalite/Freecam#88]
When not in freecam:
![2023-05-10_22 01 29](https://github.com/hashalite/Freecam/assets/57970114/20ed493a-2b08-4ae6-b4ed-d12a428ee8c0)
When in freecam:
![2023-05-10_22 01 27](https://github.com/hashalite/Freecam/assets/57970114/f2d4a0f2-5eae-43d9-884d-6ceff32994cc)

**Comment by hashalite** [comment]
This is a setting. Enable “Show Submersion Fog” in the config menu.
