### ISSUE TITLE
1.20//1.20.1 support is needed.

### ISSUE THREAD

**Issue by Zorklis** [hashalite/Freecam#89]
Thank you, love the mod

**Comment by devjta** [comment]
Made a 1.20 release. Works so far for me:
https://github.com/devjta/Freecam_devjta/releases

You can also build it for yourself, you have any doubts.

**Comment by ifcgit** [comment]
1.20.1 maybe?

**Comment by hashalite** [comment]
> 1.20.1 maybe?

Yes, coming soon

**Comment by devjta** [comment]
> 1.20.1 maybe?

Until hashalite has deployed it: https://github.com/devjta/Freecam_devjta/releases/tag/1.20.1_fix
