### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Friorianf** [hashalite/Freecam#9]
Hello.
I have an error on startup with this mod. He seems to be asking for version 17JRE , but I already have it. Please help if possible. 

![изображение](https://user-images.githubusercontent.com/27586285/153937701-7dfb5f1a-9204-4417-9cb7-b129d21cd3b7.png)
![изображение](https://user-images.githubusercontent.com/27586285/153937862-266849e7-3dba-4888-a03a-28fac34d1c62.png)
![изображение](https://user-images.githubusercontent.com/27586285/153937885-f4dfc5b8-9710-4718-8bab-38ab823cf199.png)

**Comment by hashalite** [comment]
This is an error on my part, I will release an update to fix this. Thanks for reporting.

**Comment by hashalite** [comment]
Fixed in 0.4.4.1
