### ISSUE TITLE
Some blocks still have collision, even with Ignore All Collision enabled

### ISSUE THREAD

**Issue by Aegrithas** [hashalite/Freecam#90]
The title mostly sums it up. The blocks I've found that do this are glass panes, fences, walls, iron bars, fence gates, mud, bamboo, hanging signs (just the part that has collision without freecam) and sculk shriekers (both waterlogged and not), but there may be others. Notable mentions among blocks that don't exhibit this behavior (that is, blocks whose collisions are correctly ignored) are doors, trapdoors, solid glass blocks, sculk sensors, calibrated sculk sensors, and most (as in, all that I've tried) blocks with full hitboxes (note that mud has a shorter hitbox that it appears to). The other collision settings do not seem to impact this behavior, most notably meaning that I've found no combinations of settings that remove collision for fence gates, despite being "openable" blocks.

In case it's relevant, the version of this mod that I have is v1.1.10+1.20; I'm also using Minecraft 1.20.1, Fabric Loader 0.14.21-1.20.1, Fabric API 0.83.1+1.201, and Mod Menu 7.0.1. I can also confirm that this is the same in singleplayer and online, though I haven't tried realms or LAN if that makes a difference.

**Comment by hashalite** [comment]
Thanks for reporting! This will be fixed in the next update.
