### ISSUE TITLE
collision

### ISSUE THREAD

**Issue by Latino2k7** [hashalite/Freecam#92]
the only block i cant go tru is soul sand im using the lates version on fabric and ignore all collision is enable

**Comment by hashalite** [comment]
It works for me, are you definitely using 1.2.0? If so, are you using any other mods?

**Comment by Latino2k7** [comment]
nvm i was using version 1.1.10. i download the new version 1.2.0 and is workig fine now

**Comment by hashalite** [comment]
Glad to hear it.
