### ISSUE TITLE
freecam

### ISSUE THREAD

**Issue by GamerMrAlros** [hashalite/Freecam#93]
Hi, I can't go through blocks like in previous versions

**Comment by hashalite** [comment]
Are you using 1.1.10? If so, it has a bug with collision and you should update to 1.2.0. If not, did you download the mod from Modrinth? The Modrinth version disables noclip in multiplayer to comply with their rules.

**Comment by GamerMrAlros** [comment]
oh thank you and yes I downloaded it from Modrinth

**Comment by hashalite** [comment]
No problem

**Comment by itsmorethantech** [comment]
thats a bummer, the one thing i don't like about modrinth... cheats/hacks ARE PART OF THE GAME, it is not up to modrinth to ban them i would think

**Comment by DraconicNEO** [comment]
> thats a bummer, the one thing i don't like about modrinth... cheats/hacks ARE PART OF THE GAME, it is not up to modrinth to ban them i would think

Unfortunately a lot of server owners are gatekeeping pieces of shit who seem to think there is a right and wrong way to play a sandbox game, and a lot of Minecraft's community has unfortunately decided to agree with them and enable them. Modrinth is one of those and is probably hoping that their perception as a default mod distribution hub will cement this position as the right one even further. 

I wish the community wouldn't stand for this but honestly Minecraft's community is filled with extremely dumb, useless, and submissive people. It's surprising it hasn't gotten worse.
