### ISSUE TITLE
Mud Block is acting like a wall while in free cam

### ISSUE THREAD

**Issue by WhatsJayUpTo** [hashalite/Freecam#95]
using the mod in a mangrove swamp and trying to clip into the ground like normal leaves the camera stuck on the mud blocks and acts like a wall when underground

**Comment by hashalite** [comment]
Make sure you are using 1.2.0 and not 1.1.10

**Comment by hashalite** [comment]
> Make sure you are using 1.2.0 and not 1.1.10
@WhatsJayUpTo can you check this?

**Comment by WhatsJayUpTo** [comment]
> > Make sure you are using 1.2.0 and not 1.1.10
> 
> @WhatsJayUpTo can you check this?

Sorry! got busy and forgot to relpy, and it indeed fixed the problem!

**Comment by hashalite** [comment]
Glad to hear it!
