### ISSUE TITLE
Collision with Shulkers

### ISSUE THREAD

**Issue by Royalforce1** [hashalite/Freecam#96]
Hello, very niche and not-very-important bug, but I'm currently using the 1.20.1 version of freecam mod and the camera collides with Shulkers (retracted, extended, partially extended, it always will collide). Again not a very pressing matter, but just thought I'd point it out.

**Comment by hashalite** [comment]
Thanks for reporting, this will be fixed in the next update.

**Comment by NotLicense14** [comment]
I have noticed that the freecam also collides with soul sand, fences, honey blocks, glass panes, and anything with an unusual size.

**Comment by hashalite** [comment]
> I have noticed that the freecam also collides with soul sand, fences, honey blocks, glass panes, and anything with an unusual size.

This is a separate issue that was fixed in 1.2.0. Please make sure you are on the latest version

**Comment by hashalite** [comment]
@Royalforce1 Fixed in 1.2.1
