### ISSUE TITLE
(bug) EmoteCraft emotes selection menu not opening

### ISSUE THREAD

**Issue by DearFox** [hashalite/Freecam#97]
I am using FreeCam (Modrinth Edition) 1.2.0 
Minecraft 1.20.1
And also I have the Emotecraft by KosmX mod version 2.2.7-a.build.49 installed
And while in FreeCam mode, I cannot open the emote selection menu (B key by default) neither when I control a rock, nor when I control a player in freecam view mode.

**Comment by hashalite** [comment]
The dev has a hard-coded check that ensures the camera entity is the player before opening the menu. There is not much I can do on my end, they would have to implement their own workaround. I suggest making an issue here: https://github.com/KosmX/emotes

**Comment by hashalite** [comment]
Conflicting code:
![D2127652-A0BA-4777-B140-A78F9898561C](https://github.com/hashalite/Freecam/assets/71229440/b860eb68-5892-4bcf-94a1-e08852486ba1)
