### ISSUE TITLE
Gamertag displays on player model while looking in inventory.

### ISSUE THREAD

**Issue by iL0g1c** [hashalite/Freecam#99]
Steps to reproduce:
1. Switch to Freecam
2. Open inventory.
Observed Result:
Gamertag is shown above player model in the inventory screen.

Expected result:
Gamertag is hidden.

**Comment by hashalite** [comment]
Thanks for reporting, this will be fixed in the next update.

**Comment by hashalite** [comment]
@iL0g1c Fixed in 1.2.1
